server:
  port: 8080

binance:
  apiKey: MY3CbjTmeazXaKTfqyYcAEtFHDXkofcb9bWfVyEVxJAPJGaoH7QHmnZ3ld7EejIO
  secretKey: TBa9cpuxtWDWGRLGSPBDWQAVYETawONuzEZF7Dz9vhAGyqjTTO1PsxEdotUfJEMH
  apiBaseUrl: https://api.binance.com